### ISSUE TITLE
Can not parse address like "test@example.com <test@example.com>"

### ISSUE THREAD

**Issue by wanglian** [haraka/node-address-rfc2822#36]
This module works great. 
But recently I got some emails including addresses like "test@example.com \<test@example.com\>", and can not be parsed.
```
> const emailParser = require('address-rfc2822');
> emailParser.parse("test@example.com <test@example.com>")
Error: No results
    at evalCommandPromise.then (packages/shell-server/shell-server.js:249:21)
    at runBound (domain.js:314:12)
    at bound (domain.js:301:14)
    at defaultEval (repl.js:240:29)
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at repl:1:-49
    at Object.parse (/xxxx/node_modules/address-rfc2822/index.js:20:22)
```

**Comment by msimerson** [comment]
That address format isn't correct. Unless you can point me to an RFC showing that as valid syntax, it's my opinion that this module has done the right thing.

**Comment by wanglian** [comment]
Agree totally. I looked into the RFC, @ is not a valid character for atoms.
It's not correct, but it exits. I have to find another way.
Thanks!
